name: CI

on:
  pull_request:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: playerbots
            build_playerbots: "ON"
          - tag: no-bots
            build_playerbots: "OFF"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.tag }}
            type=sha,prefix=${{ matrix.tag }}-

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_PLAYERBOTS=${{ matrix.build_playerbots }}
            USE_EXTRACTORS=OFF
            CMAKE_BUILD_TYPE=Release
            CMAKE_INSTALL_PREFIX=/opt/turtle
          cache-from: type=gha,scope=${{ matrix.tag }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag }}
          provenance: false
